// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TomlEditor
{
    internal sealed partial class Vsix
    {
        public const string Id = "TomlEditor.4e804652-a783-473b-827f-6e41f5a48b9b";
        public const string Name = "TOML Editor";
        public const string Description = @"TOML language support for Visual Studio with syntax highlighting, validation, outlining, and more...";
        public const string Language = "en-US";
        public const string Version = "1.0.901";
        public const string Author = "Mads Kristensen";
        public const string Tags = "toml, json";
        public const bool IsPreview = false;
    }
}
