// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TomlEditor
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EditorFactoryString = "3d861be2-55d5-4943-8aac-38ba31699544";
        public static Guid EditorFactory = new Guid(EditorFactoryString);

        public const string TomlEditorString = "40f7b769-cb63-4ccd-a80c-1fe6a0a07665";
        public static Guid TomlEditor = new Guid(TomlEditorString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
    }
}
